image: docker:latest

variables:
  DOCKER_IMAGE_NAME: ubuntu20-php7.4-nginx

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}
  - docker build -t ${DOCKER_IMAGE_NAME} .
  - docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_REPO}:latest
  - docker push ${DOCKER_IMAGE_REPO}:latest
  only:
  - master